### ISSUE TITLE
ValueError: "Duplicated timeseries in CollectorRegistry"

### ISSUE THREAD

**Issue by vidartf** [jupyter/jupyter_server#74] opened 2019-08-14 11:30 UTC
I'm trying to build a custom server app by inheriting from `ServerApp`. This custom app will include some other `JupyterApp`s as subcommands. So far so good. Now, I want to add a subcommand imported from another project (JupyterLab). Here, things break during import, since `jupyterlab` imports `jupyterlab_server` which import `notebook`. This causes a conflict in the metrics:

```
Traceback (most recent call last):
[...]
  File "[...]\app.py", line 6, in <module>
    from jupyterlab import labapp
  File "[...]\jupyterlab\labapp.py", line 14, in <module>
    from jupyterlab_server import slugify, WORKSPACE_EXTENSION
  File "[...]\jupyterlab_server\__init__.py", line 4, in <module>
    from .app import LabServerApp
  File "[...]\jupyterlab_server\app.py", line 9, in <module>
    from .server import ServerApp
  File "[...]\jupyterlab_server\server.py", line 20, in <module>
    from notebook.notebookapp import aliases, flags, NotebookApp as ServerApp
  File "[...]\notebook\notebookapp.py", line 80, in <module>
    from .log import log_request
  File "[...]\notebook\log.py", line 10, in <module>
    from .metrics import prometheus_log_method
  File "[...]\notebook\metrics.py", line 14, in <module>
    ['method', 'handler', 'status_code'],
  File "[...]\prometheus_client\metrics.py", line 494, in __init__
    labelvalues=labelvalues,
  File "[...]\prometheus_client\metrics.py", line 103, in __init__
    registry.register(self)
  File "[...]\prometheus_client\registry.py", line 29, in register
    duplicates))
ValueError: Duplicated timeseries in CollectorRegistry: {'http_request_duration_seconds_sum', 'http_request_duration_seconds_created', 'http_request_duration_seconds_bucket', 'http_request_duration_seconds_count'}
```

**Comment by Zsailer** [comment] 2019-12-14 00:33
Hopefully, this is solved by [nbclassic](https://github.com/zsailer/nbclassic).

**Comment by Zsailer** [comment] 2019-12-14 00:36
I don't think this is an issue with jupyter_server, though. The issue is that two apps are trying to import prometheus at the same time.

**Comment by Zsailer** [comment] 2020-04-15 16:21
I think the answer here is that ExtensionApps *should* not import prometheus directly. I believe @echarles fixed this in his [JupyterLab server extension branch](https://github.com/jupyterlab/jupyterlab_server/pull/79).

Closing for now. If this issue is still popping up, feel free to reopen! Thanks!

**Closed by Zsailer** 2020-04-15 16:21 UTC
Labels: bug
